civilcomments.settings:
  type: mapping
  label: Settings
  mapping:
    civilcomments_site_id:
      type: string
    civilcomments_content_id:
      type: string
    civilcomments_lang:
      type: string